name: qrelu-env
dependencies:
- python=3.9.16
- _tflow_select=2.2.0
- abseil-cpp=20211102.0
- absl-py=1.3.0
- aiohttp=3.8.3
- aiosignal=1.2.0
- appdirs=1.4.4
- astroid=2.11.7
- astunparse=1.6.3
- async-timeout=4.0.2
- attrs=22.1.0
- autopep8=1.6.0
- blas=1.0
- blinker=1.4
- brotlipy=0.7.0
- c-ares=1.18.1
- ca-certificates=2023.01.10
- cachetools=4.2.2
- certifi=2022.12.7
- cffi=1.15.1
- charset-normalizer=2.0.4
- click=8.0.4
- cryptography=38.0.4
- dill=0.3.6
- fftw=3.3.9
- flatbuffers=2.0.0
- flit-core=3.6.0
- frozenlist=1.3.3
- gast=0.4.0
- giflib=5.2.1
- google-auth=2.6.0
- google-auth-oauthlib=0.4.4
- google-pasta=0.2.0
- grpc-cpp=1.46.1
- grpcio=1.42.0
- h5py=3.7.0
- hdf5=1.10.6
- icu=58.2
- idna=3.4
- importlib-metadata=4.11.3
- intel-openmp=2021.4.0
- isort=5.9.3
- jpeg=9e
- keras=2.10.0
- keras-preprocessing=1.1.2
- krb5=1.19.4
- lazy-object-proxy=1.6.0
- libcurl=7.87.0
- libcxx=14.0.6
- libedit=3.1.20221030
- libev=4.33
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=11.3.0
- libnghttp2=1.46.0
- libpng=1.6.37
- libprotobuf=3.20.3
- libssh2=1.10.0
- llvm-openmp=14.0.6
- markdown=3.4.1
- markupsafe=2.1.1
- mccabe=0.7.0
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- multidict=6.0.2
- ncurses=6.4
- numpy=1.23.5
- numpy-base=1.23.5
- oauthlib=3.2.1
- openssl=1.1.1s
- opt_einsum=3.3.0
- pip=22.3.1
- platformdirs=2.5.2
- pooch=1.4.0
- protobuf=3.20.3
- pyasn1=0.4.8
- pyasn1-modules=0.2.8
- pycodestyle=2.10.0
- pycparser=2.21
- pyjwt=2.4.0
- pylint=2.14.5
- pyopenssl=22.0.0
- pysocks=1.7.1
- python=3.9.16
- python-flatbuffers=2.0
- re2=2022.04.01
- readline=8.2
- requests=2.28.1
- requests-oauthlib=1.3.0
- rsa=4.7.2
- scipy=1.10.0
- setuptools=65.6.3
- six=1.16.0
- snappy=1.1.9
- sqlite=3.40.1
- tensorboard=2.10.0
- tensorboard-data-server=0.6.1
- tensorboard-plugin-wit=1.6.0
- tensorflow=2.10.0
- tensorflow-base=2.10.0
- tensorflow-estimator=2.10.0
- termcolor=2.1.0
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- tomlkit=0.11.1
- typing-extensions=4.4.0
- typing_extensions=4.4.0
- tzdata=2022g
- urllib3=1.26.14
- werkzeug=2.2.2
- wheel=0.35.1
- wrapt=1.14.1
- xz=5.2.10
- yarl=1.8.1
- zipp=3.11.0
- zlib=1.2.13
- pip:
    - bandit==1.7.4
    - dparse==0.6.2
    - gitdb==4.0.10
    - gitpython==3.1.30
    - packaging==21.3
    - pbr==5.11.1
    - pyparsing==3.0.9
    - pyyaml==6.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - safety==2.3.5
    - smmap==5.0.0
    - stevedore==4.1.1
